# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: Legs
  joint_model_group_pose: lift
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - floating_frame
    - Rev16
    - Rev19
    - Rev30
    - Rev33
    - Rev37
    - Rev41
    - Rev45
    - Rev49
    - Rev53
    - Rev58
    - Rev61
    - Rev65
    - Rev69
    - Rev73
    - Rev77
    - Rev81
    - Rev82
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: Legs_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Rev16
      - Rev19
      - Rev30
      - Rev33
      - Rev37
      - Rev41
      - Rev45
      - Rev49
      - Rev53
      - Rev58
      - Rev61
      - Rev65
      - Rev69
      - Rev73
      - Rev77
      - Rev81
      - Rev82